blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, ContactView, Logout, PostUpdateView, PostDeleteView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('contact/', ContactView, name='contact'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),

]

csesa/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from csesa import settings
# from csesa.bot_utils import bot_loop
from csesa.views import GraderyRequestAPIView, CourseGroupTAsAPIView, DestroyGraderyRequestAPIView, AcceptTAAPIView, \
  RejectTAAPIView
from . import views

urlpatterns = [
  path('', views.index_view, name='index'),
  path('graders/<str:term_title>/', views.graders_view, name='graders'),
  path('admin/', admin.site.urls),
  # path('user/', include('users.urls', namespace='users')),
  path('board/', include('telegramboard.urls', namespace='telegramboard')),
  path('qualification/', include('qualification.urls', namespace='qualification')),

  path('api/v1/user/', include('users.urls', namespace='users')),
  path('api/v1/qualification/', include('qualification.apiv1.urls', namespace='qualification-api-v1')),
  path('api/v1/campaigns/', include('campaigns.apiv1.urls', namespace='campaigns-api-v1')),
  path('api/v1/resources/', include('resources.urls', namespace='resources-api')),



  path('api/v1/graders-with-qualification/', views.GradersWithQualificationAPIView.as_view(), name='graders-with-qualification'),
  path('api/v1/course-groups/', views.CourseGroupListAPIView.as_view(), name='graders-with-qualification'),
  path('api/v1/course-group-tas/<int:pk>', CourseGroupTAsAPIView.as_view(), name='course-group-tas'),
  path('api/v1/gradery-request/<int:pk>/', GraderyRequestAPIView.as_view(), name='gradery-request'),
                                    #^ pk is from course-group
  path('api/v1/cancel-gradery-request/<int:id>/', DestroyGraderyRequestAPIView.as_view(), name='cancel-gradery-request'),
  path('api/v1/approve-gradery-request/<int:pk>/', AcceptTAAPIView.as_view(), name='approve-gradery-request'),
  path('api/v1/reject-gradery-request/<int:pk>/', RejectTAAPIView.as_view(), name='reject-gradery-request'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# bot_loop.run_as_thread()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>
        {% block title %}
            csesa
        {% endblock title %}
    </title>

    <link rel="stylesheet" href="https://cse-shirazu.ir/assets/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" href="https://cse-shirazu.ir/yassets/semantic-ui/semantic.helper.css">
    <link rel="stylesheet" href="https://cse-shirazu.ir/yassets/semantic-ui/semantic.rtl.helper.css">
    <link rel="stylesheet" href="https://cse-shirazu.ir/yassets/font/irsans/irsans.css">
    <link rel="stylesheet" href="https://cse-shirazu.ir/yassets/swal/sweetalert.css">

    <link rel="stylesheet" href="https://cse-shirazu.ir/assets/css/base.css">


  <link rel='stylesheet prefetch' href='https://cse-shirazu.ir/assets/semantic-ui/2.4.1/components/icon.min.css'>

    {% block styles %}
    {% endblock styles %}

    <script type="text/javascript">
        (function(e,t){var n=e.amplitude||{_q:[],_iq:{}};var r=t.createElement("script");r.type="text/javascript";
        r.async=true;r.src="https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-3.0.1-min.gz.js";
        r.onload=function(){e.amplitude.runQueuedFunctions()};var i=t.getElementsByTagName("script")[0];
        i.parentNode.insertBefore(r,i);function s(e,t){e.prototype[t]=function(){this._q.push([t].concat(Array.prototype.slice.call(arguments,0)));
        return this}}var o=function(){this._q=[];return this};var a=["add","append","clearAll","prepend","set","setOnce","unset"];
        for(var u=0;u<a.length;u++){s(o,a[u])}n.Identify=o;var c=function(){this._q=[];return this;
        };var p=["setProductId","setQuantity","setPrice","setRevenueType","setEventProperties"];
        for(var l=0;l<p.length;l++){s(c,p[l])}n.Revenue=c;var d=["init","logEvent","logRevenue","setUserId","setUserProperties","setOptOut","setVersionName","setDomain","setDeviceId","setGlobalUserProperties","identify","clearUserProperties","setGroup","logRevenueV2","regenerateDeviceId"];
        function v(e){function t(t){e[t]=function(){e._q.push([t].concat(Array.prototype.slice.call(arguments,0)));
        }}for(var n=0;n<d.length;n++){t(d[n])}}v(n);n.getInstance=function(e){e=(!e||e.length===0?"$default_instance":e).toLowerCase();
        if(!n._iq.hasOwnProperty(e)){n._iq[e]={_q:[]};v(n._iq[e])}return n._iq[e]};e.amplitude=n;
        })(window,document);

        amplitude.getInstance().init("7081aaaec8edcbf42ed30ed42686947c");
    </script>

    <script src="https://cse-shirazu.ir/yassets/amplitude/amplitude.helper.js" charset="utf-8"></script>

    <script src="https://cse-shirazu.ir/yassets/vue2/vue.min.js" charset="utf-8"></script>

</head>
<body>

    {% block content %}
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cse-shirazu.ir/assets/semantic-ui/2.4.1/semantic.min.js"></script>
    <script src="https://cse-shirazu.ir/yassets/swal/sweetalert.min.js" charset="utf-8"></script>
    <script src="https://cse-shirazu.ir/yassets/swal/sweetalert.helper.js" charset="utf-8"></script>

    <script type="text/javascript">
        $('.ui.dropdown').dropdown();
    </script>

    {% block scripts %}
    {% endblock scripts %}

</body>
</html>

templates/grader-qualification-no-vote.html
<!DOCTYPE html>
<html lang="en"><!DOCTYPE html>
<html lang="fa">

  <head>

      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta charset="UTF-8">
      <title>انجمن علمی کامپیوتر</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <link rel="icon" type="image/x-icon" href="/static/img/favicon.ico">

      <script src="https://code.jquery.com/jquery-3.3.1.min.js"> </script>

      <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  </head>

  <body>
    {% for student in students %}
        {{ student.user__username }},{{ student.first_name }},{{ student.last_name }}<br />
    {% endfor %}
  </body>
</html>

templates/grader-qualification-result.html
<!DOCTYPE html>
<html lang="en"><!DOCTYPE html>
<html lang="fa">

  <head>

      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta charset="UTF-8">
      <title>انجمن علمی کامپیوتر</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <link rel="icon" type="image/x-icon" href="/static/img/favicon.ico">

      <script src="https://code.jquery.com/jquery-3.3.1.min.js"> </script>

      <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  </head>

  <body>
    <div id="navcomponent"></div>
    <div id="app"></div>
    <script src="/static/js/build.js"></script>
  </body>
</html>

templates/graders.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>
        csesa
    </title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" href="https://cse-shirazu.ir/yassets/swal/sweetalert.css">

    <link rel="stylesheet" href="https://cse-shirazu.ir/assets/css/base.css">

</head>
<body dir="rtl">
    {% if message %}
    <p>
        {{ message }}
    </p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <input placeholder="شماره دانشجویی" style="margin: 10px;" type="text" name="gid" />
        <select style="margin: 10px;" name="cid">
            <option value="-1">درس و گروه</option>
            {% for c in courses %}
            <option value="{{ c.id }}">{{ c.title }} | {{ c.group }}</option>
            {% endfor %}
        </select>
        <input type="submit" style="margin: 10px;" value="افزودن"/>
    </form>
    <table>
        <thead>
            <th>
                profile id
            </th>
            <th>
                نام
            </th>
            <th>
                نام خانوادگی
            </th>
            <th>
                شماره دانشجویی
            </th>
            <th>
                عنوان درس
            </th>
            <th>
                گروه
            </th>
            <th>
                وضعیت
            </th>
        </thead>
        <tbody>
            {% for gcr in gcrs %}
            <tr>
                <td>
                    {{ gcr.content_object.id }}
                </td>
                <td>
                    {{ gcr.content_object.user.first_name }}
                </td>
                <td>
                    {{ gcr.content_object.user.last_name }}
                </td>
                <td>
                    {{ gcr.content_object.user.username }}
                </td>
                <td>
                    {{ gcr.campaign.title }}
                </td>
                <td>
                    {{ gcr.campaign.group }}
                </td>
                <td>
                    {{ gcr.status }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block styles %}
    <style media="screen">
        .info.field p {
            font-weight: 400;
        }
    </style>
{% endblock styles %}

{% block content %}

    <div class="ui hidden divider"></div>
    <br>

    <div class="hide on mobile hard">
        <div class="ui hidden divider"></div>
        <br>
    </div>

    <div class="ui center aligned grid">
        <div class="fourteen wide mobile nine wide tablet six wide computer column">
            <div class="ui padded raised right aligned segment">

            <form class="ui form is-rtl" method="post" action="{% url 'users:login' %}">
                {% csrf_token %}

                <h2 class="ui center aligned header" style="margin-top: 13px;">ورود به سایت نظرسنجی</h2>
                <h4 class="ui center aligned header" style="margin-top: 13px;">انجمن علمی کامپیوتر</h4>

                {% if error %}
                    <div class="ten wide column">
                        <div class="ui icon rtl negative message">
                            <i class="remove icon"></i>
                            <div class="content">
                                <div class="header">
                                    اطلاعات صحیح نیست
                                </div>
                                <p>لطفا اطلاعات وارد شده را بررسی کنید</p>
                            </div>
                        </div>
                    </div>
                    <br>
                {% endif %}

                <div class="info field">
                    <p>
                        رمز عبور خود را میتوانید در <a href="https://sess.shirazu.ac.ir">sess</a>، قسمت پیام ها، با عنوان <i>"نظرسنجي انجمن علمي کامپيوتر"</i> پیدا کنید.
                    </p>
                    <p>درصورت بروز مشکل از طریق <a href="https://telegram.me/devcom_support">تلگرام</a> با ما تماس بگیرید.</p>
                </div>

                <div class="ui hidden divider"></div>


                <div class="field">
                    <div class="ui left icon input">
                        <input class="is-ltr" type="text" name="username" placeholder="شماره دانشجویی">
                        <i class="link circular mail icon"></i>
                    </div>
                </div>

                <div class="field">
                    <div class="ui left icon input">
                        <input class="is-ltr" type="password" name="password" id="pass" placeholder="رمز عبور">
                        <i class="link circular lock icon"></i>
                    </div>
                </div>

                <div class="ui hidden divider"></div>

                <div class="is-text-center">
                    <button class="ui positive large left labeled icon submit button" type="submit">
                        ورود به سایت
                        <i class="signup icon"></i>
                    </button>
                </div>

            </form>

            </div>
        </div>
    </div>

{% endblock content %}

templates/send_message.html
{% extends "base.html" %}
{% block content %}

    <div class="ui segment right aligned" style="max-width: 400px; margin: auto">

        {% if message %}
            <div class="ui positive message">
              <i class="close icon"></i>
              <p>
                  {{ message }}
              </p>
            </div>
        {% endif %}

        <div class="ui top attached tabular menu">
          <a class="item active" data-tab="first">متن</a>
          <a class="item" data-tab="second">فایل</a>
          <a class="item" data-tab="third">عکس</a>
        </div>
        <div class="ui bottom attached tab segment center aligned active" data-tab="first">
            <form class="ui form" method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                <textarea required cols='20' style='text-align:right;' name='message'
                placeholder="متن پیام"></textarea>
                <button class="ui positive button" style="margin: 10px;" type='submit'>ارسال</button>
            </form>
        </div>
        <div class="ui bottom attached tab segment center aligned" data-tab="second">
            <form class="ui form" method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                <textarea cols='20' style='text-align:right;' name='file_caption'
                placeholder="متن همراه فایل"></textarea>
                <input type='file' name='file' />
                <button class="ui positive button" style="margin: 10px;" type='submit'>ارسال</button>
            </form>
        </div>
        <div class="ui bottom attached tab segment center aligned" data-tab="third">
            <form class="ui form" method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                <textarea cols='20' style='text-align:right;' name='image_caption'
                placeholder="متن همراه عکس"></textarea>
                <input type='file' name='image' />
                <button class="ui positive button" style="margin: 10px;" type='submit'>ارسال</button>
            </form>
        </div>

        <a href="{% url 'users:logout' %}">خروج</a>
    </div>
{% endblock content %}