blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, ContactView, Logout, PostUpdateView, PostDeleteView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('contact/', ContactView, name='contact'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),

]

csesa/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from csesa import settings
# from csesa.bot_utils import bot_loop
from csesa.views import GraderyRequestAPIView, CourseGroupTAsAPIView, DestroyGraderyRequestAPIView, AcceptTAAPIView, \
  RejectTAAPIView
from . import views

urlpatterns = [
  path('', views.index_view, name='index'),
  path('graders/<str:term_title>/', views.graders_view, name='graders'),
  path('admin/', admin.site.urls),
  # path('user/', include('users.urls', namespace='users')),
  path('board/', include('telegramboard.urls', namespace='telegramboard')),
  path('qualification/', include('qualification.urls', namespace='qualification')),

  path('api/v1/user/', include('users.urls', namespace='users')),
  path('api/v1/qualification/', include('qualification.apiv1.urls', namespace='qualification-api-v1')),
  path('api/v1/campaigns/', include('campaigns.apiv1.urls', namespace='campaigns-api-v1')),
  path('api/v1/resources/', include('resources.urls', namespace='resources-api')),



  path('api/v1/graders-with-qualification/', views.GradersWithQualificationAPIView.as_view(), name='graders-with-qualification'),
  path('api/v1/course-groups/', views.CourseGroupListAPIView.as_view(), name='graders-with-qualification'),
  path('api/v1/course-group-tas/<int:pk>', CourseGroupTAsAPIView.as_view(), name='course-group-tas'),
  path('api/v1/gradery-request/<int:pk>/', GraderyRequestAPIView.as_view(), name='gradery-request'),
                                    #^ pk is from course-group
  path('api/v1/cancel-gradery-request/<int:id>/', DestroyGraderyRequestAPIView.as_view(), name='cancel-gradery-request'),
  path('api/v1/approve-gradery-request/<int:pk>/', AcceptTAAPIView.as_view(), name='approve-gradery-request'),
  path('api/v1/reject-gradery-request/<int:pk>/', RejectTAAPIView.as_view(), name='reject-gradery-request'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# bot_loop.run_as_thread()

telegram_board/urls.py
from django.urls import path
from . import views

app_name = 'telegram_board'
urlpatterns = [
    path('new/', views.send_message.as_view(), name='send'),
]

telegramboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, ContactView, Logout, PostUpdateView, PostDeleteView
from django.contrib.auth import views as auth_views

app_name = 'telegramboard'
urlpatterns = [
    path('', PostListView.as_view(), name='telegramboard-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('login/', auth_views.LoginView.as_view(template_name='telegramboard/login.html'), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('contact/', ContactView, name='contact'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),

]

telegramboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver


# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    image = models.ImageField(max_length=255, null=True, blank=True)
    file = models.FileField(blank=True, null=True)
    # date_posted = models.CharField(max_length=100, default='shd,dvb', editable=False)
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    telegram_id = models.CharField(max_length=100, default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('telegramboard:telegramboard-home')  # kwargs={'pk': self.pk})

# @receiver(post_save, sender=Post)
# def today():
#     import requests
#     from bs4 import BeautifulSoup
#
#     time_url = 'http://www.time.ir'
#     page = requests.get(time_url)
#     page_content = page.content
#
#     soup = BeautifulSoup(page_content, 'html.parser')
#
#     # print(soup)
#     # months = {'فروردین': 1, 'اردیبهشت': 2, 'خرداد': 3, 'تیر': 4, 'مرداد': 5, 'شهریور': 6,
#     #           'مهر': 7, 'آبان': 8, 'آذر': 9, 'دی': 10, 'بهمن': 11, 'اسفند': 12}
#
#     dates = soup.find('span', attrs={'class': "show date"})
#     tarikh = dates.text

telegramboard/forms.py
from django import forms
from .models import Post


class UserCreateForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    file = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'file'
        ]

telegramboard/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, Http404
from .models import Post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.contrib.messages import SUCCESS, ERROR, get_messages
from django.contrib import messages
from .forms import UserCreateForm
from csesa.settings import SEND_TO_CHAT_ID, CHANNEL_USER_NAME
from .bot_utils import bot
from pprint import pprint



# Create your views here.


class PostListView(ListView):
    model = Post
    template_name = 'telegramboard/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class PostDetailView(DetailView):
    model = Post


def send_in_bot(msg, request):
    # if msg.image is not None:
    #     print('done')
    # print(msg.file)
    # print(msg.image)
    if 'file' not in request.POST.keys():
        if request.POST['content'] != "":
            tel_id = bot.sendDocument(SEND_TO_CHAT_ID, msg.file,
                                      caption=str(msg.author) + ': \n' + str(msg.content))
        else:
            tel_id = bot.sendDocument(SEND_TO_CHAT_ID, msg.file,
                                      caption=str(msg.author))

    elif 'image' not in request.POST.keys():
        if request.POST['content'] != "":
            tel_id = bot.sendPhoto(SEND_TO_CHAT_ID, msg.image,
                                   caption=str(msg.author) + ': \n' + str(msg.content))
        else:
            tel_id = bot.sendDocument(SEND_TO_CHAT_ID, msg.image,
                                      caption=msg.author)
    else:
        tel_id = bot.sendMessage(SEND_TO_CHAT_ID, str(msg.author) + ': \n' + str(msg.content))
    return tel_id['message_id']
    # pprint(tel_id)
    # print(tel_id['message_id'])
    #
    # post = Post.objects.last()
    # print(post)
    # post.telegram_id = str(tel_id['message_id'])
    # Post.objects.last().update(telegram_id=tel_id['message_id'])
    # post.save()
    # print(post.telegram_id)


class PostCreateView(CreateView):
    model = Post
    form_class = UserCreateForm
    template_name = 'telegramboard/post_form.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_staff:
            raise Http404
        return super(PostCreateView, self).dispatch(request, *args, **kwargs)
    # fields = ['title', 'content', 'image']
    #
    def form_valid(self, form):
        #     # print(self.request.body.decode().title())
        #     # print(self.request.user)
        # print(self.request.FILES)

        ########################################################################
        flag = True
        # check for image in posts
        # if "image" in self.request.POST.keys():
        #     flag = False
        #
        # if self.request.POST['content'] != "":
        #     flag = True
        #
        # if 'file' in self.request.POST.keys():
        #     flag = False
        #
        # else:
        #     flag = flag or False

        if "image" in self.request.POST.keys() and self.request.POST[
            'content'] == "" and 'file' in self.request.POST.keys():
            flag = False

        if not flag:
            # return HttpResponse('invlkan')
            return render(self.request, 'telegramboard/error.html')
        ########################################################################

        form.instance.author = self.request.user
        form.instance.image = self.request.FILES.get('image')
        form.instance.file = self.request.FILES.get('file')
        form.instance.telegram_id = send_in_bot(form.instance, self.request)

        return super().form_valid(form)


class PostUpdateView(UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'image', 'file']

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_staff:
            raise Http404
        return super(PostUpdateView, self).dispatch(request, *args, **kwargs)

    def edit_in_telegram(self, tel_id, content, if_file):
        if if_file:
            bot.editMessageCaption((CHANNEL_USER_NAME, tel_id), caption=content)
        else:
            # print(tel_id)
            bot.editMessageText((CHANNEL_USER_NAME, tel_id), text=content)

    def form_valid(self, form):
        form.instance.author = self.request.user
        super().form_valid(form)
        post = self.get_object()
        self.edit_in_telegram(post.telegram_id,
                              str(self.request.user) + ': \n' + str(post.content),
                              post.image != '' or post.file != '')
        return super().form_valid(form)


    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(UserPassesTestMixin, DeleteView):
    model = Post

    success_url = '/board/'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_staff:
            raise Http404
        return super(PostDeleteView, self).dispatch(request, *args, **kwargs)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def delete_telegram_post(self):
        post = self.get_object()
        id = post.telegram_id
        bot.deleteMessage((CHANNEL_USER_NAME, id))
        return True

    def delete(self, request, *args, **kwargs):
        self.delete_telegram_post()
        return super(PostDeleteView, self).delete(request)


def ContactView(request):
    return render(request, 'telegramboard/contact.html')


class Logout(auth_views.LogoutView):
    def get(self, request, *args, **kwargs):
        super(Logout, self).get(request)
        return redirect('telegramboard:login')

telegramboard/templates/telegramboard/base.html
{% load static %}
<!doctype html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style>
        body {
          background: #fafafa;
          color: #333333;
          margin-top: 5rem;
        }

        h1, h2, h3, h4, h5, h6 {
          color: #444444;
        }

        ul {
          margin: 0;
        }

        .bg-steel {
          background-color: #5f788a;
        }

        .site-header .navbar-nav .nav-link {
          color: #cbd5db;
        }

        .site-header .navbar-nav .nav-link:hover {
          color: #ffffff;
        }

        .site-header .navbar-nav .nav-link.active {
          font-weight: 500;
        }

        .content-section {
          background: #ffffff;
          padding: 10px 20px;
          border: 1px solid #dddddd;
          border-radius: 3px;
          margin-bottom: 20px;
        }

        .article-title {
          color: #444444;
        }

        a.article-title:hover {
          color: #428bca;
          text-decoration: none;
        }

        .article-content {
          white-space: pre-line;
        }

        .article-img {
          height: 65px;
          width: 65px;
          margin-right: 16px;
        }

        .article-metadata {
          padding-bottom: 1px;
          margin-bottom: 4px;
          border-bottom: 1px solid #e3e3e3
        }

        .article-metadata a:hover {
          color: #333;
          text-decoration: none;
        }

        .article-svg {
          width: 25px;
          height: 25px;
          vertical-align: middle;
        }

        .account-img {
          height: 125px;
          width: 125px;
          margin-right: 20px;
          margin-bottom: 16px;
        }

        .account-heading {
          font-size: 2.5rem;
        }
    </style>

    {% if title %}
    <title>CSE Board - {{ title }}</title>
    {% else %}
    <title>CSE Board</title>
    {% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">CSE Board</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="/">خانه</a>
            <!--<a class="nav-item nav-link" href="/about">About</a>-->
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="#">ورود</a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'telegramboard:telegramboard-home' %}">CSE Board</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'telegramboard:telegramboard-home' %}">خانه</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
                <h5 class="nav-item nav-link">{{ user.username }} </h5>
                <a class="nav-item nav-link" href="{% url 'telegramboard:logout' %}">خروج</a>
                <a class="nav-item nav-link" href="{% url 'telegramboard:contact' %}">تماس با ما</a>

            {% else %}
                <a class="nav-item nav-link" href="{% url 'telegramboard:login' %}">ورود</a>
                <a class="nav-item nav-link" href="{% url 'telegramboard:contact' %}">تماس با ما</a>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>پنل شما</h3>
            <ul class="list-group">
              <li class="list-group-item list-group-item-light"><a href="{% url 'telegramboard:post-create' %}">ارسال پیام</a></li>
              <!--<li class="list-group-item list-group-item-light">Announcements</li>-->
              <!--<li class="list-group-item list-group-item-light">Calendars</li>-->
              <!--<li class="list-group-item list-group-item-light">etc</li>-->
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

telegramboard/templates/telegramboard/contact.html
{% extends "telegramboard/base.html" %}
{% block content %}
    <div class="content-section" style="text-align:right">
        <h2 style="direction:rtl">روش های تماس:</h2>
        <br>
        <p style="direction:rtl"><strong>تلفن (محمد باستین) :</strong> 09379852503</p>
        <p style="direction:rtl"><strong>تلفن (علی مهدی یار) :</strong> 09171164374</p>
        <p style="direction:rtl"><strong>ایمیل (محمد باستین) :</strong> mohamadbastin@gmail.com</p>
        <p style="direction:rtl"><strong>ایمیل (علی مهدی یار) :</strong> alimahdiyar77@gmail.com</p>
        <a style="direction:rtl" href="#"><strong>راهنما: </strong>دانلود</a>


    </div>
{% endblock content %}

telegramboard/templates/telegramboard/error.html
{% extends "telegramboard/base.html" %}
{% block content %}
    <div class="content-section">
        <h2 style="direction:rtl">حداقل یکی از فیلد های متن، عکس یا فایل را پر کنید.</h2>
        <br>
        <!--<p><strong>Phone Number:</strong> 09379852503</p>-->
        <a class="btn btn-outline-info" href="{% url 'telegramboard:post-create' %}" style="direction:rtl">بازگشت</a>
    </div>
{% endblock content %}

telegramboard/templates/telegramboard/home.html
{% extends "telegramboard/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'telegramboard:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-4' and num < page_obj.number|add:'4' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock content %}

telegramboard/templates/telegramboard/login.html
{% extends "telegramboard/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">ورود</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">ورود</button>
            </div>
        </form>
    </div>
{% endblock content %}

telegramboard/templates/telegramboard/post_confirm_delete.html
{% extends "telegramboard/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">حذف پیام</legend>
                <h2 style="direction:rtl">آیا مطمئنید میخواهید '{{ object.title }}' را حذف کنید؟ </h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">حذف</button>
                <a class="btn btn-outline-secondary" href="{% url 'telegramboard:post-detail' object.id %}">بازگشت</a>

            </div>
        </form>
    </div>
{% endblock content %}

telegramboard/templates/telegramboard/post_detail.html
{% extends "telegramboard/base.html" %}
{% block content %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="#">{{ object.author }}</a>
          <small class="text-muted">{{ object.date_objected }}</small>
          {% if object.author == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'telegramboard:post-update' object.id %}">ویرایش</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'telegramboard:post-delete' object.id %}">حذف</a>
            </div>
          {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
          {% if object.image %}
        <img src="{{ object.image.url }}" style="max-width:700px; max-height:700; ">
          {% endif %}
          {% if object.file %}
          <div>
          <a href="{{ object.file.url }}">{{ object.file }}</a>
          </div>
          {% endif %}
      </div>
    </article>
{% endblock content %}

telegramboard/templates/telegramboard/post_form.html
{% extends "telegramboard/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">ایجاد پیام</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">ارسال</button>
        </div>
    </form>
</div>
{% endblock content %}

telegramboard/templates/telegramboard/telegram_board_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ارسال اطلاعیه</title>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"> </script>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.js"></script>

    <script>
        $(document).ready(function(){
            $('.menu .item').tab();

            $('.message .close')
              .on('click', function() {
                $(this)
                  .closest('.message')
                  .transition('fade')
                ;
              });

        });
    </script>
</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

telegramboard/templates/telegramboard/telegram_board_template.html
{% extends "base.html" %}
{% block content %}

    <div class="ui segment right aligned" style="max-width: 400px; margin: auto">

        {% if message %}
            <div class="ui positive message">
              <i class="close icon"></i>
              <p>
                  {{ message }}
              </p>
            </div>
        {% endif %}

        <div class="ui top attached tabular menu">
          <a class="item active" data-tab="first">متن</a>
          <a class="item" data-tab="second">فایل</a>
          <a class="item" data-tab="third">عکس</a>
        </div>
        <div class="ui bottom attached tab segment center aligned active" data-tab="first">
            <form class="ui form" method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                <textarea required cols='20' style='text-align:right;' name='message'
                placeholder="متن پیام"></textarea>
                <button class="ui positive button" style="margin: 10px;" type='submit'>ارسال</button>
            </form>
        </div>
        <div class="ui bottom attached tab segment center aligned" data-tab="second">
            <form class="ui form" method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                <textarea cols='20' style='text-align:right;' name='file_caption'
                placeholder="متن همراه فایل"></textarea>
                <input type='file' name='file' />
                <button class="ui positive button" style="margin: 10px;" type='submit'>ارسال</button>
            </form>
        </div>
        <div class="ui bottom attached tab segment center aligned" data-tab="third">
            <form class="ui form" method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                <textarea cols='20' style='text-align:right;' name='image_caption'
                placeholder="متن همراه عکس"></textarea>
                <input type='file' name='image' />
                <button class="ui positive button" style="margin: 10px;" type='submit'>ارسال</button>
            </form>
        </div>

        <a href="{% url 'users:logout' %}">خروج</a>
    </div>
{% endblock content %}

telegramboard/templates/telegramboard/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>wefvfev</title>
</head>
<body>

<h2>Hello</h2>

</body>
</html>